import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import HeaderPage from "./component/header";
import Marquee from "./component/marqueeText";
import Navbar from "./component/navbar";
import Footer from "./component/footer";
import { Suspense } from "react";
import { Toast } from "@heroui/react";

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="bn" className={`${hindSiliguri.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">
        <Toast.Provider placement="top end">
        <HeaderPage />
        <Suspense fallback={<div className="h-12 border-b border-black/10" />}>
          <Navbar />
        </Suspense>
        <Suspense fallback={<div className="h-10 border-b" />}>
          <Marquee />
        </Suspense>
        <Suspense
          fallback={
            <main className="container mx-auto flex-1 px-4 py-12">
              লোড হচ্ছে...
            </main>
          }
        >
          {children}
        </Suspense>
        <Footer/>
        </Toast.Provider>
      </body>
    </html>
  );
}
